
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: newApp_development
  username: ubuntu
  password: ubuntu
  host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #min_messages: notice

test:
  <<: *default
  database: newApp
  username: ubuntu
  password: ubuntu

production:
  <<: *default
  database: newApp_production
  username: ubuntu
  password: ubuntu
